# Generated by Django 4.1.5 on 2023-01-16 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[
                    ("Normal", "Normal"),
                    ("Refill", "Refill"),
                    ("Offline", "Offline"),
                ],
                default="Offline",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="snack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="myapp.snack"
            ),
        ),
    ]
