# Generated by Django 4.1.5 on 2023-01-15 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="status",
            field=models.CharField(
                choices=[("Normal", "Normal"), ("Out of Stock", "Out Of Stock")],
                default="Out of Stock",
                max_length=20,
            ),
        ),
    ]
